# input
#   - mandatory
#       * target_username: user to config env to
#
---

    - name: transfer the setup-env script
      become_user: "{{ target_username }}"
      template: src="{{ target_username }}-install.sh.j2"
        dest="/tmp/{{ target_username }}-install.sh"
        mode=0700

    - name: run setup-env script
      become_user: "{{ target_username }}"
      shell: "/tmp/{{ target_username }}-install.sh"

